FluentWebApplication1/Models/Customer.cs
#nullable disable
using System.ComponentModel.DataAnnotations;
using WebValidationLibrary1.Interfaces;
using WebValidationLibrary1.Models;
// ReSharper disable NotNullOrRequiredMemberIsNotInitialized
#pragma warning disable CS1591 // Missing XML comment for publicly visible type or member

namespace FluentWebApplication1.Models;
/// <summary>
/// Represents a customer with personal and identification details.
/// </summary>
/// <remarks>
/// This class includes properties for storing customer information such as name, date of birth,
/// social security number, gender, and identification details. It is designed to be used in 
/// scenarios where customer data needs to be validated and processed.
/// </remarks>
public class Customer : INames, IGender, IBirthDate
{
    public int Id { get; set; }
    
    [Display(Name = "Birth date")]
    public DateOnly? DateOfBirth { get; set; }

    [Display(Name = "Social Security Number")]
    public string SocialSecurityNumber { get; set; }

    [Display(Name = "First name")]
    public string FirstName { get; set; }

    [Display(Name = "Middle name")]
    public string MiddleName { get; set; }

    [Display(Name = "Last name")]
    public string LastName { get; set; } 

    public Gender? Gender { get; set; }

    public override string ToString() => $"{FirstName} {LastName}  {Gender}";

}

FluentWebApplication1/Models/Gender.cs
namespace FluentWebApplication1.Models;

/// <summary>
/// Represents the gender of an individual.
/// </summary>
/// <summary>
/// Gender is unspecified or not provided.
/// </summary>
/// <summary>
/// Male gender.
/// </summary>
/// <summary>
/// Female gender.
/// </summary>
public enum Gender
{
    Unspecified = 0,
    Male = 1,
    Female = 2
}

FluentWebApplication1/Models/IBirthDate.cs
namespace FluentWebApplication1.Models;

public interface IBirthDate
{
    DateOnly? DateOfBirth { get; set; }
}

FluentWebApplication1/Pages/About.cshtml.cs
using FluentWebApplication1.Classes;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.RazorPages;

namespace FluentWebApplication1.Pages
{
    public class AboutModel : PageModel
    {
        public string CurrentPageName { get; private set; }
        public void OnGet()
        {
 
            CurrentPageName = PageHelpers.GetCurrentPageName(HttpContext.Request);
        }
    }
}

FluentWebApplication1/Pages/Error.cshtml.cs
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.RazorPages;
using System.Diagnostics;

namespace FluentWebApplication1.Pages;
[ResponseCache(Duration = 0, Location = ResponseCacheLocation.None, NoStore = true)]
[IgnoreAntiforgeryToken]
public class ErrorModel : PageModel
{
    public string? RequestId { get; set; }

    public bool ShowRequestId => !string.IsNullOrEmpty(RequestId);

    private readonly ILogger<ErrorModel> _logger;

    public ErrorModel(ILogger<ErrorModel> logger)
    {
        _logger = logger;
    }

    public void OnGet()
    {
        RequestId = Activity.Current?.Id ?? HttpContext.TraceIdentifier;
    }
}

FluentWebApplication1/Pages/Index.cshtml.cs
using FluentValidation;
using FluentValidation.AspNetCore;
using FluentWebApplication1.Classes;
using FluentWebApplication1.Models;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.RazorPages;
using Serilog;
using WebValidationLibrary1.LanguageExtensions;

namespace FluentWebApplication1.Pages;

/// <summary>
/// Represents the model for the Index page in the FluentWebApplication1 application.
/// </summary>
/// <remarks>
/// This class is responsible for handling the logic and data binding for the Index page.
/// It utilizes FluentValidation to validate the <see cref="Customer"/> model. 
/// The class inherits from <see cref="PageModel"/>, which provides the base functionality 
/// for Razor Pages in ASP.NET Core.
/// </remarks>
public class IndexModel(IValidator<Customer> validator) : PageModel
{

    /// <summary>
    /// Gets or sets the customer information.
    /// </summary>
    [BindProperty]
    public Customer Customer { get; set; } = new();
    
    

    /// <summary>
    /// Initializes a new instance of the <see cref="IndexModel"/> class.
    /// </summary>
    /// <returns></returns>
    public IActionResult OnGet()
    {
        Customer = new Customer() { SocialSecurityNumber = "106823302" };
        return Page();
    }

    /// <summary>
    /// Handles the submission of the form by validating the <see cref="Customer"/> model.
    /// </summary>
    /// <returns>
    /// A <see cref="PageResult"/> indicating the result of the operation. 
    /// If validation fails, the page is re-rendered with validation errors added to the model state.
    /// If validation succeeds, the page is re-rendered for further processing.
    /// </returns>
    /// <remarks>
    /// This method uses FluentValidation to validate the <see cref="Customer"/> object. 
    /// Validation errors are logged to the console (not recommended for production use) 
    /// and added to the model state for display on the page.
    /// </remarks>
    public PageResult OnPostSubmit()
    {
        // Perform validation
        var result = validator.Validate(Customer);
        if (!result.IsValid)
        {
            Log.Information("Validation failure on page {PageName} {@errors}", 
                PageHelpers.GetCurrentPageName(HttpContext.Request), result.ToJson());
            result.AddToModelState(ModelState);
        }

        return Page();
    }

}

FluentWebApplication1/Pages/About.cshtml
@page
@model FluentWebApplication1.Pages.AboutModel
@{
}

<h1>About</h1>

FluentWebApplication1/Pages/Index.cshtml
@page

@model IndexModel
@{
    ViewData["Title"] = "Customer Information";
}

<div class="container my-4" >

    <div class="card shadow">

        <div class="card-body p-4">

            <h1 class="mb-4 fs-6">Customer Information</h1>

            <form method="post">

                <div asp-validation-summary="ModelOnly"></div>

                <div class="col-12 mb-2">
                    <div class="col-12 col-md-12">
                        <label asp-for="Customer.DateOfBirth" for="picker" class="form-label"></label>
                        <input asp-for="Customer.DateOfBirth" 
                               id="picker" 
                               class="form-control" 
                               style="width: 200px" 
                               type="date"/>
                        <span class="text-danger small fw-bold" asp-validation-for="Customer.DateOfBirth"></span>
                    </div>
                </div>

                <div class="col-12 col-md-12 mb-2">
                    <label asp-for="Customer.SocialSecurityNumber" class="form-label"></label>
                    <input asp-for="Customer.SocialSecurityNumber" 
                           style="width: 120px" 
                           class="form-control"/>
                    <span class="text-danger small fw-bold" asp-validation-for="Customer.SocialSecurityNumber"></span>
                </div>

                <div class="col-12 col-md-6 mb-2">
                    <label asp-for="@Model.Customer.FirstName" class="form-label"></label>
                    <input asp-for="@Model.Customer.FirstName"
                           class="form-control"/>
                    <span class="text-danger small fw-bold" asp-validation-for="Customer.FirstName"></span>
                </div>

                <div class="col-12 col-md-6 mb-2">
                    <label asp-for="Customer.MiddleName" class="form-label"></label>
                    <input asp-for="Customer.MiddleName" 
                           class="form-control" 
                           style="width: 250px"/>
                    <span class="text-danger small fw-bold" asp-validation-for="Customer.MiddleName"></span>
                </div>

                <div class="col-12 col-md-6 mb-2">
                    <label asp-for="@Model.Customer.LastName" class="form-label"></label>
                    <input asp-for="@Model.Customer.LastName" 
                           class="form-control"/>
                    <span class="text-danger small fw-bold" asp-validation-for="Customer.LastName"></span>
                </div>

                
                <div class="col-12 col-md-6">
                    <div class="row g-2 align-items-center">
                        <div class="col-auto">
                            <label asp-for="Customer.Gender" class="col-form-label"></label>
                        </div>
                        <div class="col">
                            <select class="form-select" style="width: 145px" asp-for="Customer.Gender" >
                                <option value="" >Select...</option>
                                <option value="Male">Male</option>
                                <option value="Female">Female</option>
                                <option value="Unspecified">Unspecified</option>
                            </select>
                            <span class="text-danger small fw-bold" asp-validation-for="Customer.Gender"></span>
                        </div>
                    </div>
                </div>

                <div class="row g-3 mt-3">

                    <!-- Submit -->
                    <div class="col-12">
                        <input type="submit" value="Continue" asp-page-handler="Submit" class="btn btn-primary mt-2"/>
                    </div>
                </div>
            </form>
        </div>
    </div>
</div>


@* 
Client-side validation
https://learn.microsoft.com/en-us/aspnet/core/mvc/models/validation?view=aspnetcore-9.0#client-side-validation
*@
@section Scripts {
    @{
        await Html.RenderPartialAsync("_ValidationScriptsPartial");
    }
}

FluentWebApplication1/Pages/Shared/_Layout.cshtml
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - fluent web application1</title>
    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css" />
    <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/@@fortawesome/fontawesome-free@6.5.1/css/all.min.css">
    <link rel="stylesheet" href="~/css/site.css" asp-append-version="true" />
    <link rel="stylesheet" href="~/FluentWebApplication1.styles.css" asp-append-version="true" />
</head>
<body>
    <header>
        <nav class="navbar navbar-expand-sm navbar-toggleable-sm navbar-light bg-white border-bottom box-shadow mb-3">
            <div class="container">

                <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target=".navbar-collapse" aria-controls="navbarSupportedContent"
                        aria-expanded="false" aria-label="Toggle navigation">
                    <span class="navbar-toggler-icon"></span>
                </button>

                <div class="navbar-collapse collapse d-sm-inline-flex justify-content-between ">
                    <ul class="navbar-nav flex-grow-1">
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-page="/Index">Home</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-page="/About">About</a>
                        </li>
                    </ul>
                    <div class="me-4">
                        <svg xmlns="http://www.w3.org/2000/svg" width="16" height="16" fill="currentColor" class="bi bi-battery-full" viewBox="0 0 16 16">
                            <path d="M2 6h10v4H2z" />
                            <path d="M2 4a2 2 0 0 0-2 2v4a2 2 0 0 0 2 2h10a2 2 0 0 0 2-2V6a2 2 0 0 0-2-2zm10 1a1 1 0 0 1 1 1v4a1 1 0 0 1-1 1H2a1 1 0 0 1-1-1V6a1 1 0 0 1 1-1zm4 3a1.5 1.5 0 0 1-1.5 1.5v-3A1.5 1.5 0 0 1 16 8" />
                        </svg>
                    </div>

                </div>
            </div>
        </nav>
    </header>
    <div class="container">
        <main role="main" class="pb-3">
            @RenderBody()
        </main>
    </div>

    <footer class="border-top footer text-muted">
        <div class="container">
            FluentValidation demo
        </div>
    </footer>

    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
    <script src="~/js/site.js" asp-append-version="true"></script>

    <script src="https://unpkg.com/bootstrap-show-password@1.3.0/dist/bootstrap-show-password.min.js"></script>

    @await RenderSectionAsync("Scripts", required: false)
</body>
</html>